language: java
sudo: false

cache:
  directories:
  - "$HOME/.m2"

before_script: 
  - echo 'site-deploy'

jobs:
  include:
  - stage: build
    jdk: oraclejdk8
    script: 
    - ls -l
    - cd ./site-deploy
    - mvn compile
    - mvn exec:java -Dexec.mainClass="org.chaoscoffee.HTMLTemplateUtils"
    - ls -l
    - cd ..
    - git clone https://${GH_REF}
    - ls -l
    - mv ./site-deploy/result.html ./site/cn/index.html -f
    - rm -rf site-deploy
    - cd ./site
    - git checkout master
    - git config user.name "ChaosCoffee"
    - git add .
    - git commit -m "update site by travis-ci"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - dev

env:
 global:
   - GH_REF: github.com/ChaosCoffee/site.git